# .github/release.yml

changelog:
  categories:
    - title: Fixed 🛠
      labels:
        - bug
    - title: Added 🎉
      labels:
        - enhancement
    - title: Changed
      labels:
        - "*"
