name: lint

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/style-fix.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: pint

      - name: Run Pint
        run: pint --test
