name: lint

on:
  push:
    branches: master
    paths:
      - "**.php"
      - ".github/workflows/lint.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: pint:1.x, cs2pr
          coverage: none

      - name: Run Pint
        run: pint --test --format=checkstyle | cs2pr
